# Dockerfile - Flutter
FROM instrumentisto/flutter:latest

ENV DEBIAN_FRONTEND=noninteractive

# Installer des outils nécessaires (réduits car pas besoin de dépendances graphiques)
RUN apt-get update && apt-get install -y \
    curl \
    git \
    vim \
    php-cli \
    php-mysql \
    && apt-get clean 

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers du projet dans le container
COPY . /app

RUN flutter pub get
RUN flutter pub run flutter_native_splash:create

# Commande par défaut
CMD ["bash"]