services:
  flutter:
    build:
      context: ./projet_flutter
      dockerfile: Dockerfile
    container_name: flutter_app
    volumes:
      - ./projet_flutter:/app
    working_dir: /app
    command: ["flutter", "run", "-d", "web-server", "--web-port=3000", "--web-hostname=0.0.0.0"]
    ports:
      - "3000:3000"  # Port pour l'application Flutter Web
    networks:
      - app_network

  php:
    image: php:8.0-apache
    container_name: php_app
    volumes:
      - ./api_php:/var/www/html  # Répertoire de ton backend PHP
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: my_database
    ports:
      - "8080:80"  # Port pour accéder à l'API PHP
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"  # Port pour accéder à la base de données MySQL
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge